spring:
  profiles:
    active: local

server:
  port: 8080

mybatis:
  mapper-locations: classpath:/mybatis/**/*.xml
  type-aliases-package: com.wms.flowerwms
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info